import src.domain.entities.agent_profile as agent_profile_entity
import src.domain.entities.patient as patient_entity
import src.services.agentic.prompts.prompt_section as prompt_section
import src.services.agentic.state_models as agentic_state_models


class PromptAssembler:
    def __init__(self, sections: list[prompt_section.PromptSection]) -> None:
        self._sections = sections

    def build_runtime_prompt(
        self,
        runtime_context: agentic_state_models.RuntimePromptContext,
        known_patient: patient_entity.Patient | None,
        agent_profile: agent_profile_entity.AgentProfile | None = None,
    ) -> str:
        all_lines: list[str] = []
        for section in self._sections:
            all_lines.extend(section.render(runtime_context, known_patient, agent_profile))
        return "\n".join(all_lines)

    def compose_full_prompt(
        self,
        base_system_prompt: str,
        runtime_context: agentic_state_models.RuntimePromptContext,
        known_patient: patient_entity.Patient | None,
        agent_profile: agent_profile_entity.AgentProfile | None = None,
    ) -> str:
        runtime_prompt = self.build_runtime_prompt(runtime_context, known_patient, agent_profile)
        return (
            f"{base_system_prompt}\n\n### Runtime Context (Generated by Backend)\n{runtime_prompt}"
        )
