import src.domain.entities.patient as patient_entity
import src.services.agentic.prompts.enabled_tools_section as enabled_tools_section
import src.services.agentic.prompts.patient_profile_section as patient_profile_section
import src.services.agentic.prompts.prompt_assembler as prompt_assembler
import src.services.agentic.prompts.runtime_context_section as runtime_context_section
import src.services.agentic.prompts.state_instructions as state_instructions
import src.services.agentic.state_models as agentic_state_models


def _build_default_assembler() -> prompt_assembler.PromptAssembler:
    return prompt_assembler.PromptAssembler(
        sections=[
            runtime_context_section.RuntimeContextSection(),
            patient_profile_section.PatientProfileSection(),
            enabled_tools_section.EnabledToolsSection(),
            state_instructions.StateInstructionsSection(),
        ]
    )


class RuntimePromptBuilder:
    def __init__(
        self,
        assembler: prompt_assembler.PromptAssembler | None = None,
    ) -> None:
        if assembler is None:
            self._assembler = _build_default_assembler()
        else:
            self._assembler = assembler

    def compose_base_and_runtime_system_prompt(
        self,
        base_system_prompt: str,
        runtime_prompt: str,
    ) -> str:
        return (
            f"{base_system_prompt}\n\n### Runtime Context (Generated by Backend)\n{runtime_prompt}"
        )

    def build_runtime_system_prompt(
        self,
        runtime_context: agentic_state_models.RuntimePromptContext,
        known_patient: patient_entity.Patient | None,
    ) -> str:
        return self._assembler.build_runtime_prompt(runtime_context, known_patient)

    def build_runtime_state_specific_instructions(
        self,
        runtime_context: agentic_state_models.RuntimePromptContext,
    ) -> list[str]:
        return state_instructions._instructions_for_state(runtime_context)
